### ISSUE TITLE
Search Field on Start View

### ISSUE THREAD

**Issue by marthaler** [kguelseven/monithor#5]
Hi

A Search on the Start View leads to the second List View without the search Results, In the second Page i have to insert the Search criteria a second Time.  A search on the first View would be nice, just to reduce the Elements there...

Merci
:-)

**Comment by kguelseven** [comment]
Mit #7 ist das erste Problem behoben. Frage 2 braucht etwas mehr Aufwand und ist für die Bedienung nicht zwingend notwendig finde ich :).
